### ISSUE TITLE
How to upload video to Vimeo from Android app?

### ISSUE THREAD

**Issue by coneits** [vimeo/vimeo-deeplink-android#16] opened 2016-09-22 10:30 UTC
Hello.

I would like to upload video to vimeo from my android app.
Can I upload video from my android app using your github repository?
Or is there any other published github source code that can upload video?

Thanks,
Look forward to hearing from you.

Best Regards.

**Comment by kevinzetterstrom** [comment] 2016-09-22 11:53
Closing - duplicate of #17

**Closed by kevinzetterstrom** 2016-09-22 11:53 UTC
