### ISSUE TITLE
VimeoDeeplink.showVideoWithUri on Android TV platform not working

### ISSUE THREAD

**Issue by tlammens** [vimeo/vimeo-deeplink-android#25] opened 2017-09-19 13:37 UTC
#### Issue Summary
VimeoDeeplink.showVideoWithUri method is not working on Android TV, is this intentional?

#### Reproduction Steps
Detailed steps to reproduce the issue.
Using VimeoDeeplink.showVideoWithUri the same way as in normal Android on phones or tablets.

#### Expected Behavior
Vimeo app starts at given video uri

#### Actual Behavior
Vimeo app opens but on start page not at the video uri

**Comment by kevinzetterstrom** [comment] 2017-09-19 13:52
Hi @tlammens thanks for reporting the issue. This is expected behavior right now, since the Vimeo Android TV app does not have support for deep links. Perhaps in a future version of the TV app we will have support for deep linking. For now, I will update the readme of this repository to clarify that it is a helper for the mobile app only.

**Comment by kevinzetterstrom** [comment] 2017-09-19 20:07
We have updated the readme for clarity in #26 - closing this with that change.

**Closed by kevinzetterstrom** 2017-09-19 20:07 UTC
